/** Declaration file generated by dts-gen */
declare module 'passport-oauth2' {
    export class Strategy {
        constructor(options: any, verify: any);
    
        userProfile(token: any, tokenSecret: any, params: any, done: any): any;
        authenticate(req: any, options: any): any;
        requestTokenParams(options: any): any;
        userAuthorizationParams(options: any): any;
        userProfile(token: any, tokenSecret: any, params: any, done: any): any;
    }
}

declare module 'passport-oauth2-refresh' {
    const x: any;  
    export = x;
}

declare module 'cookie-session' {  
    const x: any;  
    export = x;
}

declare module 'yahoo-fantasy' {
    const x: any;
    export = x;
}

declare module 'node-stattleship' {
    const x: any;  
    export = x;
}
